\documentclass[english,12pt]{article}
\usepackage{fontspec}
\setmainfont{FreeSerif}
\setsansfont{FreeSans}
\setmonofont{FreeMono}
\usepackage[letterpaper,left=1in,right=1in,top=1in,bottom=1in,headheight=14pt]{geometry}
\usepackage{url}
\usepackage{fancyhdr}
\usepackage{graphicx}
\usepackage[bf]{caption}
\usepackage{rotating}
\usepackage{wrapfig}
\usepackage{booktabs}
\usepackage{float}
\usepackage{multirow}
\usepackage{setspace}
\usepackage{txfonts}
\usepackage{fancyref}
\usepackage{acronym}
\usepackage{array}
\usepackage{dcolumn}
\usepackage{adjustbox}
\usepackage{longtable}
\usepackage{pdflscape}
\usepackage[backend=biber,natbib=true,hyperref=true,style=numeric-comp]{biblatex}
\addbibresource{references.bib}
\usepackage[noblocks,auth-sc]{authblk}
\usepackage[hyperfigures,bookmarks,colorlinks]{hyperref}
%\usepackage[hyperfigures,bookmarks,colorlinks,citecolor=black,filecolor=black,linkcolor=black,urlcolor=black]{hyperref}
% Floats at end for journals
% \usepackage[nolists,figuresfirst,nomarkers,heads,nofighead,notabhead]{endfloat}
% \AtBeginFigures{\section*{Figure Legends}\renewcommand{\efloatseparator}{\hbox{}}}
% \AtBeginTables{\section*{Tables}\renewcommand{\efloatseparator}{\mbox{}}}
\usepackage[nomargin,inline,draft]{fixme}
\newcommand{\DLA}[1]{\textcolor{red}{\fxnote{DLA: #1}}}
\usepackage[x11names,svgnames]{xcolor}
\usepackage{texshade}
\usepackage{tikz}
\usepackage{nameref}
\usepackage{xspace}
% this package will stretch the font slightly if necessary.
\usepackage{microtype}
\usepackage{zref-xr,zref-user}
\newenvironment{narrow}[2]{%
  \begin{list}{}{%
      \setlength{\topsep}{0pt}%
      \setlength{\leftmargin}{#1}%
      \setlength{\rightmargin}{#2}%
      \setlength{\listparindent}{\parindent}%
      \setlength{\itemindent}{\parindent}%
      \setlength{\parsep}{\parskip}}%
  \item[]}{\end{list}}
\def\newblock{\hskip}
\newenvironment{paperquote}{%
  \begin{quote}%
     \it
  }%
  {\end{quote}}
\renewcommand{\textfraction}{0.15}
\renewcommand{\topfraction}{0.85}
\renewcommand{\bottomfraction}{0.65}
\renewcommand{\floatpagefraction}{0.60}
%\renewcommand{\baselinestretch}{1.8}
\newenvironment{enumerate*}%
  {\begin{enumerate}%
    \setlength{\itemsep}{0pt}%
    \setlength{\parskip}{0pt}}%
  {\end{enumerate}}
\newenvironment{itemize*}%
  {\begin{itemize}%
    \setlength{\itemsep}{0pt}%
    \setlength{\parskip}{0pt}}%
  {\end{itemize}}
\oddsidemargin 0.0in 
\textwidth 6in
\raggedbottom
\clubpenalty = 10000
\widowpenalty = 10000
\pagestyle{fancy}

\begin{document}
\author[1]{Don Armstrong}
\author[1,2]{Monica Uddin}
\author[1,3,*]{Derek E. Wildman}
\title{Human tissue specific markers}
\affil[1]{Institute for Genomic Biology, University of Illinois at Urbana-Champaign, Urbana, IL, USA}
\affil[2]{Department of Psychology, University of Illinois at Urbana-Champaign, Urbana, IL, USA}
\affil[3]{Department of Molecular and Integrative Physiology, University of Illinois at Urbana-Champaign, Urbana, IL, USA}
\affil[*]{To whom correspondence should be addressed}
\date{\today}

\input{acronyms}

\maketitle

\doublespacing

<<load.libraries,echo=FALSE,results="hide",warning=FALSE,message=FALSE,error=FALSE,cache=FALSE>>=
opts_chunk$set(dev="cairo_pdf",out.width="\\textwidth",out.height="0.7\\textheight",out.extra="keepaspectratio")
#opts_chunk$set(cache=TRUE, autodep=TRUE)
options(device = function(file, width = 8, height = 7, ...) {
  cairo_pdf(tempfile(), width = width, height = height, ...)
})
options(scipen = -1, digits = 2)
library("data.table")
library("ggplot2")
library("reshape2")
library("proto")
library("xtable")
library("caret")
library("pROC")
library("grid")

capwords <- function(s, strict = FALSE) {
    cap <- function(s) paste(toupper(substring(s, 1, 1)),
                             {s <- substring(s, 2); if(strict) tolower(s) else s},
                             sep = "", collapse = " " )
    sapply(strsplit(s, split = " "), cap, USE.NAMES = !is.null(names(s)))
}

@ 


<<load.data,echo=FALSE,results="hide",warning=FALSE,cache.extra=tools::md5sum(paste0("../tissue_specific_expression/",c("tissue_specific_markers","interesting_gene_reads_wide","combined_star_logs","svm_test_results","svm_test_results_reduced")))>>=
for (a in paste0("../tissue_specific_expression/",
                 c("tissue_specific_markers",
                   "interesting_gene_reads_wide",
                   "combined_star_logs",
                   "svm_test_results",
                   "svm_test_results_reduced"
                   ))) {
    load(a)
}
tissue.specific.genes <- data.table(tissue.specific.genes)
setkey(tissue.specific.genes,"gene")
@ 

<<specific.markers.plot.function,echo=FALSE,results="hide",warning=FALSE>>=
specific.markers.plot <- function(tissue.name,genes) {
    setkey(interesting.gene.reads.wide,"gene_short_name")
    if (missing(genes))
        genes <- as.character(tissue.specific.genes[tissue==tissue.name,gene])
    interesting.tissues <- 
        colnames(interesting.gene.reads.wide)[
         apply(interesting.gene.reads.wide[genes,-(1:2),with=FALSE],1,
                             function(x){order(-x)[2]+2})]
    
    interesting.tissues <- 
        c("gene_short_name",tissue.name,unique(interesting.tissues))
    
    tissue.specific.gene.reads <- 
        data.table(melt(interesting.gene.reads.wide[genes,interesting.tissues,with=FALSE],
                        id="gene_short_name",
                        variable.name="tissue",
                        value.name="FPKM"
                        ))
    tissue.specific.gene.reads[,`log_2(FPKM)`:=log2(FPKM+1)]
    gene.levels <- 
        unique(as.character(tissue.specific.genes[tissue==tissue.name][order(specificity),gene]))
    tissue.specific.gene.reads[,gene_short_name:=factor(gene_short_name,levels=gene.levels)]
    return(ggplot(tissue.specific.gene.reads,
                  aes(y=gene_short_name,
                          x=tissue))
           + geom_tile(aes(fill=`log_2(FPKM)`))
           + scale_fill_gradient(limits=c(0,17),
                                 low="white",
                                 high="#002058",
                                 guide=guide_colourbar(title=expression(log[2](FPKM))))
           + scale_x_discrete("", expand = c(0, 0))
           + scale_y_discrete("", expand = c(0, 0))
           + theme_grey(base_size=14)
           + theme(legend.position = "top",
                   axis.ticks = element_blank(),
                   panel.grid=element_blank(),
                   panel.border=element_blank(),
                   panel.background=element_blank(),
                   plot.background=element_blank(),
                   plot.margin=unit(c(1,1,1,1),"mm"),
                   axis.text.x = element_text(angle = 30, hjust = 1, vjust=1))
           )
}
@ 

\section{Abstract}


\section{Introduction}

\acp{EV} are small (40-1000nm) compartments that can be found in
blood, saliva, and urine. \acp{EV} originate from the plasma membrane
or multivesicular endosome of many cell types and contain proteins,
lipids, mRNA, miRNA, and many other non-coding RNAs. Because \acp{EV}
contain mRNA from the cell of origin and can be obtained without
invasive procedures, they are a promising remote sensor of the
transcriptome of tissues that would otherwise be inaccessible.
    
One requirement for remotely sensing the transcriptome is identifying
the source tissue of a specific \ac{EV}. To identify the source tissue
of a specific \ac{EV}, we have identified miRNA and mRNA markers which
are characteristic of multiple organs and tissues from existing
publicly-available RNAseq transcriptomes by calculating a tissue
specificity index.
    
The tissue specificity index for gene $g$ ($\tau_g$) is
    
\begin{equation}
  \tau_g = \frac{\sum_{i=1}^{i=N} \left(1-\frac{X_{i,g}}{\mathrm{max}(X_g)}\right)}{N-1}
\end{equation}
\label{eq:tissue_specificity_index}
    
where $N$ is the number of tissues, $X_{i,g}$ is the mean expression
of gene $g$ in tissue $i$ and $\mathrm{max}(X_g)$ is the maximal
expression of gene $g$ across all tissues.
    
We also trained a multiclass \ac{SVM} to accurately identify the
tissue of origin, and present the results of the identification of
reads from uterine and placental origin here. Tables showing tissue
specific genes from all
\Sexpr{length(unique(na.omit(tissue.specific.genes[,tissue])))}
tissues can be found on \url{http://dla2.us/p/em2015}.

\section{Methods}

\Sexpr{star.logs[grepl("Number of input reads",field),sum(as.numeric(value))]} %
%
RNAseq reads from %
%
\Sexpr{length(star.logs[grepl("Number of input reads",field),value])} %
% 
samples (supplemented with FPKMs from
\Sexpr{nrow(predictions.caret.svm[["uterus"]][["training"]])+
  nrow(predictions.caret.svm[["uterus"]][["testing"]]) -
  length(star.logs[grepl("Number of input reads",field),value])} %
%
additional samples without raw data in the \ac{SRA}) corresponding
to %
\Sexpr{length(unique(na.omit(tissue.specific.genes[,tissue])))} %
different tissues were obtained from the Roadmap Epigenomics
\cite{Bernstein.ea2010:NIHRoadmapEpigenomicsMapping} and GTEx
\cite{Gtexconsortium.2015:Thegenotypetissueexpression} projects, as
well as uterine (GSE50599,
\cite{Chan.ea2014:Assessmentofmyometrialtranscriptome}) and placenta
(GSE66622, \cite{Hughes.ea2015:Evaluatingintra-andinter-individual})
samples from the \ac{SRA}.
    
Reads were aligned to \textit{Homo sapiens} reference genome GRCh38
with Ensembl annotation release 80 using STAR v2.4.2a
\cite{Dobin.ea2013:STARultrafastuniversalRNA-seq} and called using
Tophat 2 v2.0.10
\cite{Trapnell.ea2009:TopHatdiscoveringsplicejunctions}. The average
percentage of uniquely mapped reads was %
\Sexpr{mean(as.numeric(gsub("%","",star.logs[field=="Uniquely mapped reads %",value])))}\%
and the average total mapping percentage was %
\Sexpr{mean(as.numeric(gsub("%","",star.logs[field=="Uniquely mapped reads %",value]))+as.numeric(gsub("%","",star.logs[field=="% of reads mapped to multiple loci",value])))}\%.
% 
For samples where the reads were not publicly available (GTEx and
some Roadmap Epigenomics samples), the RPKM were taken from publicly
available result files (see code for details).

The \ac{SVM} was generated using caret
\cite{Kuhn2008:Buildingpredictivemodelsinr} and svmRadial
\cite{Karatzoglou2004:kernlab} with 10 cycles of 10 repeats and a tune
length of 8 with a training set representing $\approx 75\%$ of the
samples ($\approx 2450$ samples total, including $\approx 35$ uterine
or $\approx 60$ placenta) in each of the groups chosen at random, with
the remaining samples making up a testing set ($\approx 820$ samples).
 

\section{Results}


\subsection{Uterus Specific}
<<uterus.specific.markers.table,results="asis",echo=FALSE>>=
temp <- tissue.specific.genes[tissue=="uterus",
                              list(gene,tissue,specificity,gi.max)]
setorder(temp,-gi.max)
setnames(temp,c("Gene","Tissue","Tissue Specificity","Mean Expression"))
print(xtable(temp,
             caption="Uterus specific genes",label="tab:uterus_specific_genes"),
      include.rownames=FALSE,
      )
rm(temp)
@ 

\begin{figure}
<<uterus.specific.markers.figure,fig.width=8,fig.height=8,echo=FALSE>>=
print(specific.markers.plot("uterus")
      + xlab("Genes Characteristic of Uterus ")
      + ylab("Tissue"))
@
\caption{Expression of genes characteristic of uterus
  ($\tau_g \ge 0.98$) in uterus and all tissues with the second
  highest expression for any of the uterus-characterizing genes
  ordered by their tissue specificity. The known uterus-characterizing
  gene PAEP and short RNAs ZNFX1-AS1\_3 (87bp) and AL356310.1 (94bp)
  are highly characteristic of uterus.}
\label{fig:uterus_specific_markers}
\end{figure}

FTX\_1 is very interseting

PCP4 is troubling, because this is a purkingie cell protein

Some of the markers which we had previously seen (and in fact mention
in our abstract have gone away).

We originally identified MIR1914, MIR126, SNORD12, and SNORD5 as
uterus specific. MIR1914 is actually placenta specific, as is MIR126.

This occured because the placenta FPKMs we based the original list on
did not properly align against miRNA or snRNA
\fref{tab:missing_uterus_specific_genes}. The uterus calls also appear
to be wrong or cooked; for example, SNORD5 has counts of 7000ish which
are not inside of its confidence interval. This may be indicative of a
off-by-one error or something else that is screwed up in their file.

<<missing.uterus.specific.markers.table,results="asis",echo=FALSE>>=
temp <- tissue.specific.genes[c("MIR1914","MIR126","SNORD12","SNORD5"),
                              list(gene,tissue,specificity,gi.max)]
setnames(temp,c("Gene","Tissue","Tissue Specificity","Mean Expression"))
print(xtable(temp,
             caption="Missing previously uterus specific genes",
             label="tab:missing_uterus_specific_genes"),
      include.rownames=FALSE,
      )
rm(temp)
@ 

\subsection{Placenta Specific Genes}

<<placenta.specific.markers.table,results="asis",echo=FALSE>>=
temp <- tissue.specific.genes[tissue=="placenta" & gi.max > 100,
                              list(gene,tissue,specificity,gi.max)]
setorder(temp,-gi.max)
setnames(temp,c("Gene","Tissue","Tissue Specificity","Mean Expression"))
print(xtable(temp,
             caption="Placenta specific genes",label="tab:placenta_specific_genes"),
      include.rownames=FALSE,
      floating=FALSE,
      tabular.environment="longtable"
      )
rm(temp)
@ 

\begin{figure}
<<placenta.specific.markers.figure,fig.width=8,fig.height=8,echo=FALSE>>=
print(specific.markers.plot("placenta",
                            genes=as.character(tissue.specific.genes[tissue=="placenta" & 
                                                                         gi.max >= 1024
                               ,gene]))
      + xlab("Genes Characteristic of Placenta")
      + ylab("Tissue"))
@

}
\caption{Expression of genes characteristic of placenta
  ($\tau_g \ge 0.98$) with high expression ($\mathrm{FPKM} \ge 1024$)
  in placenta and all tissues with the second highest expression for
  any placenta-characterizing gene ordered by their specificity to
  placenta. The previously known placenta-characterizing PSG genes and
  CSH genes are nearly unique to placenta and the short RNAs mir-126,
  mir-622, and PAPPA-AS1 are less so.}
\label{fig:placenta_specific_markers}
\end{figure}


\subsection{Identification of Tissue source of Exosomes}

\begin{figure}
<<placenta.roc.curve,fig.width=8,fig.height=8,echo=FALSE>>=
layout(matrix(c(1,3,2,4),2,2))
pl.roc.obj1 <- 
    plot.roc(as.numeric(predictions.caret.svm[["placenta"]][["testing"]][,"actual"])-1,
             as.numeric(predictions.caret.svm[["placenta"]][["testing"]][,"placenta"]),
             percent=TRUE,
             ## main="Training vs Testing set for Uterus",
             col="#002058"
             )
pl.roc.obj2 <- 
    lines.roc(as.numeric(predictions.caret.svm[["placenta"]][["training"]][,"actual"])-1,
              as.numeric(predictions.caret.svm[["placenta"]][["training"]][,"placenta"]),
              percent=TRUE,
              col="#E87722")
# testobj <- roc.test(rocobj1, rocobj2)
# text(50, 50, labels=paste("p-value =", format.pval(testobj$p.value)), adj=c(0, .5))

legend("bottomright",
       legend=c("Placenta Testing Set", "Placenta Training Set"),
       col=c("#002058", "#E87722"),
       lwd=2)

ut.roc.obj1 <- 
    plot.roc(as.numeric(predictions.caret.svm[["uterus"]][["testing"]][,"actual"])-1,
             as.numeric(predictions.caret.svm[["uterus"]][["testing"]][,"uterus"]),
             percent=TRUE,
             ## main="Training vs Testing set for Uterus",
             col="#002058"
             )
ut.roc.obj2 <- 
    lines.roc(as.numeric(predictions.caret.svm[["uterus"]][["training"]][,"actual"])-1,
              as.numeric(predictions.caret.svm[["uterus"]][["training"]][,"uterus"]),
              percent=TRUE,
              col="#E87722")
# testobj <- roc.test(rocobj1, rocobj2)
# text(50, 50, labels=paste("p-value =", format.pval(testobj$p.value)), adj=c(0, .5))

legend("bottomright",
       legend=c("Uterus Testing Set", "Uterus Training Set"),
       col=c("#002058", "#E87722"),
       lwd=2)

for (a in c("placenta","uterus")) {
pl.roc.obj1 <- 
    plot.roc(as.numeric(predictions.caret.svm.reduced[[a]][["testing.1000.reads"]][,"actual"])-1,
             as.numeric(predictions.caret.svm.reduced[[a]][["testing.1000.reads"]][,a]),
             percent=TRUE,
             ## main="Training vs Testing set for Uterus",
             col="#002058"
             )
pl.roc.obj2 <- 
    lines.roc(as.numeric(predictions.caret.svm.reduced[[a]][["testing.5000.reads"]][,"actual"])-1,
              as.numeric(predictions.caret.svm.reduced[[a]][["testing.5000.reads"]][,a]),
              percent=TRUE,
              col="#E87722")
pl.roc.obj3 <- 
    lines.roc(as.numeric(predictions.caret.svm.reduced[[a]][["testing.10.reads"]][,"actual"])-1,
              as.numeric(predictions.caret.svm.reduced[[a]][["testing.10.reads"]][,a]),
              percent=TRUE,
              col="green")
pl.roc.obj4 <- 
    lines.roc(as.numeric(predictions.caret.svm.reduced[["placenta"]][["testing.1.reads"]][,"actual"])-1,
              as.numeric(predictions.caret.svm.reduced[["placenta"]][["testing.1.reads"]][,"placenta"]),
              percent=TRUE,
              col="brown")
# testobj <- roc.test(rocobj1, rocobj2)
# text(50, 50, labels=paste("p-value =", format.pval(testobj$p.value)), adj=c(0, .5))

legend("bottomright",       legend=paste0(capwords(a)," ",c("1 Read","10 Reads","1000 Reads", "5000 Reads")),
       col=c("brown","green","#002058", "#E87722"),
       lwd=2)
}
grid.text(c("A","B","C","D"),
          x=unit(c(0,0.5,0,0.5),"npc"),
          y=unit(c(1,1,0.5,0.5),"npc"),
          just=c("left","top"),
          gp=gpar(fontsize=32)
          )

@

\caption{\ac{ROC} curve of the placenta \ac{SVM} (A) and
  uterus \ac{SVM} (B) . Both \ac{SVM} are highly effective at
  distinguishing between samples of uterus origin and non-uterus
  origin.
  %
  \ac{ROC} curve of reduced reads in Placenta and
  Uterus samples with the indicated number of total reads. Reads were
  reduced by sampling reads for each sample weighted by the FPKM
  measured for each sample, and run using the same trained SVM
  depicted in Figure \ref{fig:plac_ut_full_roc}. %
  % 
  The placenta \ac{SVM} is fairly accurate at distinguishing between
  samples of placental origin and non-placental origin even when the
  number of reads is very low (10). The uterus \ac{SVM} requires many
  more reads in order to achieve similar accuracy. This is likely due
  to the much smaller number of uterus specific genes in comparison to
  placenta.}
\label{fig:plac_ut_roc}
\end{figure}

\begin{figure}
\label{fig:plac_ut_red_roc}
\end{figure}

\section{Discussion}


\section{Conclusion}

  \begin{itemize}
  \item Pregnancy-specific glycoproteins (PSG1, 2, 3 et al.) are
    characteristic of placental tissues, and PAEP is characteristic of
    uterus, as previously described.
%   \item Numerous Long-noncoding RNA and smaller RNAs are specific to uterus and placenta
  \item \ac{SVM} are able to accurately identify the tissue of origin
    for uterus and placenta.
  \item Very few sequenced reads are required to accurately identify
    tissues of Placental origin. We are able to detect 100\% of the
    placenta tissues with 80\% specificity with just 10 reads.
  \item We can easily identify exosomes originating from the placenta,
    as even the smallest exosomes can contain 70 RNA molecules
    \cite{Li.ea2014:AnalysisofRNAcontent}.
  \item Non-maternal variants may also be able to distinguish between
    placental reads and maternal reads.
  \end{itemize}


\printbibliography

\end{document}
